### ISSUE TITLE
Parsing urls with missing protocol

### ISSUE THREAD

**Issue by lusy** [medialize/URI.js#187]
Hi, I've just used URI.js for the first time and I was excited:

```javascript
var urlParser = require('URIjs');

urlParser("http://example.com:8080/pathname/lala").protocol() --> http
urlParser("http://example.com:8080/pathname/lala").hostname() --> example.com
urlParser("http://example.com:8080/pathname/lala").port() --> 8080
urlParser("http://example.com:8080/pathname/lala").pathname() --> /pathname/lala
```
However, if I try it on a url where the protocol part is missing, everything gets messed up:

```javascript
var urlParser = require('URIjs');

urlParser("example.com:8080/pathname/lala").protocol() --> example.com
urlParser("example.com:8080/pathname/lala").hostname() --> 
urlParser("example.com:8080/pathname/lala").port() --> 
urlParser("example.com:8080/pathname/lala").pathname() --> 8080/pathname/lala
```

Could we do support for parsing urls where the protocol part is missing? I think they come up pretty often.. Should I pull-request that? Or is it intetionally left out? Thanks!

**Comment by ooxi** [comment]
That will not be really possible since `example.com:8080/pathname/lala` is no valid URI. There is support for URIs without the scheme part in URI.js but in your example that would be `://example.com:8080/pathname/lala`

**Comment by rodneyrehm** [comment]
This behavior has caused confusion in the past and I fully expect this to raise more issues in the future. Welcome to the weird world of string semantics…

According to [RFC 3986](http://tools.ietf.org/html/rfc3986) the string `example.com:8080/pathname/lala` is to be considered an URN with the scheme `example.com` and the path `8080/pathname/lala`, which URI.js is getting right. To treat this as an HTTP URL, either prepend the proper scheme, or use the scheme-relative notation presented by @ooxi
