### ISSUE TITLE
Error parsing specific URI

### ISSUE THREAD

**Issue by SunilAgrawal** [medialize/URI.js#190]
When I parse the below URI I get somewhat incorrect results, particular the 'hostname' field.

https://moe.linkedinlabs.com:443/pal2/v1/people::(email=XXX@XXX.example.com):public:(id,first-name,last-name,distance,picture-url,site-standard-profile-request,headline,industry,LOCATION:(name),three-current-positions:(title,company:(id,name)))?trk=MOE&ver=16&escape=html&_=1424816267333

I get hostname to include the port number and the port as null.

**Comment by rodneyrehm** [comment]
I'm not sure I can reproduce your problem, as the following looks good to me. What's your code look like?

```js
var s = 'https://moe.linkedinlabs.com:443/pal2/v1/people::(email=XXX@XXX.example.com):public:(id,first-name,last-name,distance,picture-url,site-standard-profile-request,headline,industry,LOCATION:(name),three-current-positions:(title,company:(id,name)))?trk=MOE&ver=16&escape=html&_=1424816267333';
var u = URI(s);

console.log(JSON.stringify(u._parts, null, 2));
// prints
 {
  "protocol": "https",
  "username": null,
  "password": null,
  "hostname": "moe.linkedinlabs.com:443",
  "urn": null,
  "port": null,
  "path": "/pal2/v1/people::(email=XXX@XXX.example.com):public:(id,first-name,last-name,distance,picture-url,site-standard-profile-request,headline,industry,LOCATION:(name),three-current-positions:(title,company:(id,name)))",
  "query": "trk=MOE&ver=16&escape=html&_=1424816267333",
  "fragment": null,
  "duplicateQueryParameters": false,
  "escapeQuerySpace": true
}

console.log(u.hostname());
//prints:
"moe.linkedinlabs.com:443"
```

**Comment by SunilAgrawal** [comment]
Shouldn't the hostname only have the name of the host, and the port number
have '443'? Why is the port number null?

**Comment by rodneyrehm** [comment]
good catch! fixed in master.

**Comment by SunilAgrawal** [comment]
When will this make the mainline? I usually use the online build tool to get a custom build of URI.js.

**Comment by rodneyrehm** [comment]
> When will this make the mainline?
now: [v1.14.2](https://github.com/medialize/URI.js/releases/tag/v1.14.2)
