### ISSUE TITLE
Serializing non-ascii querys returns wrong result

### ISSUE THREAD

**Issue by Sebmaster** [medialize/URI.js#198]
Compare the following testcase of URIjs vs the native browser URL constructor:

```js
URI("http://example.org/?ä").toString() // 'http://example.org/?ä'
URI("http://example.org/").query("ä").toString() // 'http://example.org/?ä'
new URL("http://example.org/?ä").toString() // 'http://example.org/?%C3%A4'
```

Seems like URIjs violates the [URL Living Standard](https://url.spec.whatwg.org/#query-state) at point 1.3.1, no?

**Comment by rodneyrehm** [comment]
URI.js is not and has never been compliant to the URL Living Standard. The latter was informed by the former. I'm considering switching out my parser for [URL](https://github.com/Polymer/URL) (or my own implementation of the algorithm, if I'm bored enough) in URI.js 2.0.

URI.js does not mutate the parsed data unless you make it. At this point I have a hard time classifying this as a bug…

```js
// target output: "http://example.org/?%C3%A4"

// inital parse needs to be normalized
URI("http://example.org/?ä").normalize().toString()
// setting literal string needs to be normalized
URI("http://example.org/").query("ä").normalize().toString()
// using accessor properly escapes values
URI("http://example.org/").addQuery('ä').toString()
URI("http://example.org/").addQuery({'ä':null}).toString()
```

**Comment by Sebmaster** [comment]
Oh, I see, it wasn't clear to me that URI.js doesn't aim to be compliant to the standard.

Thanks for the link to URL, might be worth having a look at.
