### ISSUE TITLE
Consistently encode spaces

### ISSUE THREAD

**Issue by barneycarroll** [medialize/URI.js#199]
I'm trying to persist a search query, which can include spaces, to the route.
```javascript
URI().addSearch( 'foo', 'bar ' ).toString()
// http://medialize.github.io/URI.js/docs.html?foo=bar+

URI().addSearch( 'foo', encodeURIComponent( 'bar ' ) ).toString()
// http://medialize.github.io/URI.js/docs.html?foo=bar%2520
```

What I'd like is:
```javascript
// http://medialize.github.io/URI.js/docs.html?foo=bar%20
```

What am I doing wrong?

**Comment by rodneyrehm** [comment]
[URI.encodeQuery()](http://medialize.github.io/URI.js/docs.html#static-encodeQuery) can be told to handle spaces either as `%20` or as `+` explicitly, or via the global [escapeQuerySpace](http://medialize.github.io/URI.js/docs.html#setting-escapeQuerySpace) property. The (irritating) `+` comes from [`application/www-form-url-encoded`](https://html.spec.whatwg.org/multipage/forms.html#application/x-www-form-urlencoded-encoding-algorithm).

**Comment by rodneyrehm** [comment]
I figure this question was answered…
