### ISSUE TITLE
URITemplate remove unused paramaters.

### ISSUE THREAD

**Issue by raysuelzer** [medialize/URI.js#203]
Would the authors of this library be interested in adding an option to the `expand` function on URITemplate that will remove unused templates variables?  I'm going to have to write this for my own use case, but will put in a PR if it is something that would be welcomed.

**Comment by rodneyrehm** [comment]
[3.2.1 Variable Expansion](http://tools.ietf.org/html/rfc6570#section-3.2.1) says:

> A variable that is undefined (Section 2.3) has no value and is ignored by the expansion process.  If all of the variables in an expression are undefined, then the expression's expansion is the empty string.

And the implementation follows suit:

```js
var tpl = new URITemplate('/{foo}-{bar}/');
tpl.expand({}) === '/-/';
```

If that is not what you meant by "remove unused template variables", please elaborate.

**Comment by raysuelzer** [comment]
Weird.  I am getting undefined-undefined.  let me play around with it a bit more.

**Comment by raysuelzer** [comment]
Okay totally bizarre, it now works as you described.  Maybe I was typing something wrong.
