### ISSUE TITLE
An exception is thrown when using URI() without the new keyword

### ISSUE THREAD

**Issue by KyleNeedham** [medialize/URI.js#205]
When URI is used without the new keyword it will return a new instance of itself passing both an `url` and `base` parameter.

```javascript
if (!(this instanceof URI)) {
  return new URI(url, base);
}
```

Since these parameters are both undefined at this point, it is caught by the undefined check on the url and then also passes the check on the arguments length, throwing a `TypeError`.

```javascript
if (url === undefined) {
  if (arguments.length) {
    throw new TypeError('undefined is not a valid argument for URI');
  }
```

**Comment by rodneyrehm** [comment]
I can reproduce the issue.

**Comment by rodneyrehm** [comment]
fixed in master. can you wait for `1.15.1` a bit?

**Comment by KyleNeedham** [comment]
Yeah sure that's fine.
