### ISSUE TITLE
! parsed as valid hostname

### ISSUE THREAD

**Issue by pimterry** [medialize/URI.js#207]
Hostnames are only allowed to contain a-z 0-9 . - according to RFC 952: http://tools.ietf.org/html/rfc952.

However:

```javascript
new URI("http://!").hostname(); // returns '!'
```

I'm not sure what your approach to validation of input is (potentially this should throw an exception, or there should be an API to check the validity of this somewhere?). At the very least though, I'd expect `.hostname()` to return an empty string in this case. Is that possible?

**Comment by rodneyrehm** [comment]
How did you stumble across this? Are you dealing with user input? Are you scanning text for links?

> Hostnames are only allowed to contain a-z 0-9 . - according to RFC 952

that may have been true back in 1985, but it's certainly not true anymore: [Internationalized Domain Name](http://en.wikipedia.org/wiki/Internationalized_domain_name). Also see the [URL spec](http://url.spec.whatwg.org/).

---

In a modern browser (e.g. Chrome), run the following in the DevTools:

```js
var u = new URL('http://!');
JSON.stringify(u, null, 2);
```
You will see that the parsed host is `%21` (percent escaped "!").
```js
{
  "hash": "",
  "search": "",
  "pathname": "/",
  "port": "",
  "hostname": "%21",
  "host": "%21",
  "password": "",
  "username": "",
  "protocol": "http:",
  "origin": "http://%21",
  "href": "http://%21/"
}
```

> I'm not sure what your approach to validation of input is

The approach is to consider everything legal that does not make URI itself stumble - liberal input, strict(er) output.

>  At the very least though, I'd expect .hostname() to return an empty string in this case. Is that possible?

Sure, it's possible to implement, but unlikely to be shipped in URI.js.

**Comment by pimterry** [comment]
Ah, yes, fair point about internationalized domain names now. Doh. I'm taking user inputted URLs, not scanning for them, and my tests caught it (I'd assumed it'd be an obvious invalid URL case).

I think it's somewhat surprising behaviour, but it's not super important to me. Given Chrome accepts it too  I'm happy to close this (might be good to add some notes to the docs on how URI.js handles invalid URLs though, I didn't find any explanation covering this anywhere).
