### ISSUE TITLE
Object constructor doesn't support aliases

### ISSUE THREAD

**Issue by graingert** [medialize/URI.js#212]
I'd expect:
```javascript
> new URI({scheme: 'http', pathname:'/'}).toString()
'http:///'
```

But I actually get:

```javascript
> new URI({scheme: 'http', pathname:'/'}).toString()
'[object Object]'
```

**Comment by rodneyrehm** [comment]
The `[object Object]` is created in [URI.parse](https://github.com/medialize/URI.js/blob/gh-pages/src/URI.js#L1052-L1069) in a section that is trying to deal different default object structures. Serializing these objects and then parsing the url again is the simplest way to get around these issues.

[URI._parse()](https://github.com/medialize/URI.js/blob/gh-pages/src/URI.js#L178-L193) defines the properties used internally. If you want to pass an object, it currently must use those keys, as noted in [the docs](http://medialize.github.io/URI.js/docs.html#constructor).

This works:

```js
new URI({ protocol: 'http', path: '/' }).toString()
// "http:///"
```
