### ISSUE TITLE
Possibility of adding .noConflict()

### ISSUE THREAD

**Issue by m4ss1m0g** [medialize/URI.js#215]
Sharepoint pages already declare a URI object and obviously your lib doesn't work. 
I slightly mod your code:

<em>
// First declare a Object
var URIJS = {};

// .. lower I pass the new object instead of <b>this</b>
}(URIJS, function (punycode, IPv6, SLD, root) {

</em>

**Comment by ooxi** [comment]
I really don't think `.noConflict` is necessary. It's an archaism from pre amd times. Simply use a module system like requirejs and URIjs will not bind to the global namespace (since this does not reference window but the constructor scope)

**Comment by rodneyrehm** [comment]
URI.js has had [`.noConflict()`](http://medialize.github.io/URI.js/docs.html#static-noConflict) for quite a while…
