### ISSUE TITLE
URL parsing does not work - don't know why

### ISSUE THREAD

**Issue by DirkStevens** [medialize/URI.js#216]
Hello @medialize - looks like this url is not parsed properly?

http://hello.demo.be/#/views/FilterDashboard/D_OneDimension?SelectAggr…ectMeasure=Sales&SelectDimension1=Category&:embed=yes&:tabs=no&:toolbar=no

I tried uri.getSearch(true) and wanted to get the query "object" from "SelectAggr…ectMeasure=Sales&SelectDimension1=Category&:embed=yes&:tabs=no&:toolbar=no"

Doesn't work - could you tell me what I am doing wrong?

**Comment by rodneyrehm** [comment]
You are correct. the multiple `:` are causing problems.

**Comment by DirkStevens** [comment]
Thanks @rodneyrehm - since it was the first time using the library I wasn't sure.

**Comment by rodneyrehm** [comment]
My bad, I only had a quick glance at the URL and didn't see the `#` in there. URI is correctly parsing your URL:

```js
var input = 'http://hello.demo.be/#/views/FilterDashboard/D_OneDimension?SelectAggr…ectMeasure=Sales&SelectDimension1=Category&:embed=yes&:tabs=no&:toolbar=no';
var uri = URI(input);
```
is parsed to:

```js
{
  "protocol": "http",
  "username": null,
  "password": null,
  "hostname": "hello.demo.be",
  "urn": null,
  "port": null,
  "path": "/",
  "query": null,
  "fragment": "/views/FilterDashboard/D_OneDimension?SelectAggr…ectMeasure=Sales&SelectDimension1=Category&:embed=yes&:tabs=no&:toolbar=no",
}
```

this is not a bug.

**Comment by DirkStevens** [comment]
Thanks @rodneyrehm - 

Could you tell me why the part of the URI that starts with "?" is not truly a querystring because of the "#" ?  I guess this is about some intricacies of URIs?

**Comment by rodneyrehm** [comment]
Have a look at [Understanding URIs](http://medialize.github.io/URI.js/about-uris.html) - specifically the ASCII chart detailing the components. You're being tricked by thinking `?` is more important than `#`, while it's the other way around. Everything past the first `#` is considered the fragment (or hash, as its commonly referred to as well).
