### ISSUE TITLE
Resource-relative URI doesn't get a scheme after calling absoluteTo()

### ISSUE THREAD

**Issue by abbakym** [medialize/URI.js#219]
Consider the use case:
````
var u = new URI('//example.com/path');
u = u.absoluteTo('http://example.com');
u.scheme() // undefined
````

My intuitive assumption was that after such treatment the URI will get a scheme. However I understand that the URI is already "absolute", so calling "absoluteTo" on it is strange.

**Comment by rodneyrehm** [comment]
[`.absoluteTo()`](http://medialize.github.io/URI.js/docs.html#absoluteto) resolves the `path` of the given (relative) URL against the (absolute) base URL's `path`, adding the `authority` when possible. For a given URL that already is absolute, `.absoluteTo()` is a no-op.

I think the behavior is correct. Do we need to improve the docs on this?

**Comment by abbakym** [comment]
Improvement on docs sounds nice. I guess it's the nature of "resource-relative" URLs that's causing confusion. On one hand, they are absolute, on the other hand, they have "relative" in their name.

**Comment by rodneyrehm** [comment]
docs modified in master
