### ISSUE TITLE
parseQuery TypeError when first group reference is null

### ISSUE THREAD

**Issue by rur** [medialize/URI.js#220]
URI.parseQuery('?test&test=123')
	=> TypeError: Cannot read property 'push' of null

	URI.parseQuery('?test=123&test')
	=> {"test" : ["123",null]}

Also, should parse query pass through invalid URI components?

	URI.parseQuery('?%=123')
	=> {"%" : "123"}

**Comment by rodneyrehm** [comment]
> `URI.parseQuery('?test&test=123')`

interesting, a bug indeed.

> Also, should parse query pass through invalid URI components?

yes, I think that's fine.

**Comment by rodneyrehm** [comment]
fixed in master

**Comment by rur** [comment]
awesome, thanks
