### ISSUE TITLE
.segmentCoded([…]) does not encode slashes

### ISSUE THREAD

**Issue by bradleyayers** [medialize/URI.js#223]
The problem lies with this usage:

    > URI("/").segmentCoded(["fo/o", "bar"]).toString()
    "/fo/o/bar"

I would have expected it to behave as:

    > URI("/").segmentCoded(["fo/o", "bar"]).toString()
    "/fo%2Fo/bar"

Interesting it's fine when _not_ using an array argument, and instead using multiple invocations:

    URI("/").segmentCoded("fo/o").segmentCoded("bar").toString()
    "/fo%2Fo/bar"

**Comment by rodneyrehm** [comment]
for some reason array input was decoded instead of encoded. obviously a bug. fix is in master. thank you!

**Comment by bradleyayers** [comment]
Awesome, thanks!
