### ISSUE TITLE
.relativeTo() requires trailing slash on .. path segments

### ISSUE THREAD

**Issue by bradleyayers** [medialize/URI.js#224]
I'm not sure if this adheres to the URI spec or not, but this behaviour was surprising to me:

    > URI("http://example.com/foo/..").relativeTo("http://example.com/foo/").toString()
    ""
    > URI("http://example.com/foo/../").relativeTo("http://example.com/foo/").toString()
    "../"

What are your thoughts here?

**Comment by rodneyrehm** [comment]
The problem was located in `.normalizePath()` returning `""` (empty string) for `"/foo/.."` but `"/"` for `"/foo/../"`. This issue is resolved and pushed to master. Thank you!

**Comment by bradleyayers** [comment]
Once again I'm very impressed with your responsiveness. Thank-you very much!
