### ISSUE TITLE
jspm package?

### ISSUE THREAD

**Issue by chovy** [medialize/URI.js#225]
Can we get it working with jspm?

**Comment by rodneyrehm** [comment]
since I don't use jspm, you may want to elaborate on what has to be done to achieve that…

**Comment by rodneyrehm** [comment]
Apparently it's not that important…

**Comment by AndreSteenveld** [comment]
Firstly sorry for digging this one up but it is something I have just started working on.

@rodneyrehm: jspm is a package manager for much like bower but aimed at smoothing out the differences between the current packaging systems (AMD, CJS, ES6, etc). You can find more info at http://jspm.io

I am going to give this one a shot using the information from https://github.com/medialize/URI.js/issues/118

**Comment by rodneyrehm** [comment]
Very well :)

**Comment by AndreSteenveld** [comment]
Well it actually just worked out of the box... (big anti climax). Just for documention sake this are the steps you need to take to install, include and use URI.js in a system where you are using jspm as your primary package manager.

1. ```$ jspm install uri```
2. In the file you want to use it import it using ```System.import( "uri" ).then( ... );``` or if you are using ES6 import it using ```import URI from "uri";". 

As far as I can tell now this just all works.

**Comment by rodneyrehm** [comment]
do you want to send a PR to update README.md accordingly?

**Comment by AndreSteenveld** [comment]
Sure, I'll do that tonight

**Comment by siulung4073** [comment]
+1
