### ISSUE TITLE
.relativeTo() requires trailing slash

### ISSUE THREAD

**Issue by bradleyayers** [medialize/URI.js#226]
This seems related to #224, but is a little different:

    > URI("http://example.com/").relativeTo("http://example.com/foo").toString()
    ""
    > URI("http://example.com/foo/").relativeTo("http://example.com/foo/bar").toString()
    ""

I expected either `.` or `./`.

**Comment by rodneyrehm** [comment]
Are you sure the order correct? `URI(target).relativeTo(base)` - you seem to be running `URI(base).relativeTo(target)`. Anyway, I agree that in this particular case the result should be `./`

**Comment by bradleyayers** [comment]
Yeah it's the correct order, I admit the first example is quite weird, but the second is likely more common. I stumbled on this case during some testing.

**Comment by rodneyrehm** [comment]
fixed in master
