### ISSUE TITLE
bower.json lists multiple files of the same filetype for "main" option

### ISSUE THREAD

**Issue by bradleyayers** [medialize/URI.js#227]
https://github.com/bower/bower.json-spec#main explicitly states that only one file per filetype should be listed in `main`:

> The entry-point files necessary to use your package. Only one file per filetype.

    "main": [
      "src/URI.js",
      "src/IPv6.js",
      "src/SecondLevelDomains.js",
      "src/punycode.js",
      "src/URITemplate.js",
      "src/jquery.URI.js",
      "src/URI.min.js",
      "src/jquery.URI.min.js",
      "src/URI.fragmentQuery.js",
      "src/URI.fragmentURI.js"
    ],

I would expect only **one** `.js` file here.

**Comment by AntoineReneleau** [comment]
:+1:
Same issue here, I only need URI.min.js and all the others modules and jQuery are installed by Bower.

**Comment by bradleyayers** [comment]
The documentation also states:

> Do not include minified files.

So we want to only include `src/URI.js` rather than `src/URI.min.js`.

**Comment by AntoineReneleau** [comment]
My bad, ```src/URI.js``` will do it just fine.

**Comment by rodneyrehm** [comment]
… and it's in master as well…

**Comment by AntoineReneleau** [comment]
Thanks a lot ! When can we expect a release for that ?

**Comment by rodneyrehm** [comment]
right now I'd make that depend on @bradleyayers' testing efforts. if he thinks he's done and no more issues pop up, I'm happy to release 1.15.2 - but I'd not want to release that, just to see him raise more issues hours later ;)

**Comment by AntoineReneleau** [comment]
Ok.
Another question : should the lib still depends on jQuery since the jQuery plugin isn't anymore in bower.json ?

**Comment by rodneyrehm** [comment]
hm… it probably shouldn't. The jQuery binding should probably be moved to a separate repository… :/

**Comment by bradleyayers** [comment]
I've finished my current stint of testing, so I'm in favour of a new release.

**Comment by AntoineReneleau** [comment]
Thanks for your work. Waiting for the release :+1:

**Comment by rodneyrehm** [comment]
[v1.15.2](https://github.com/medialize/URI.js/releases/tag/v1.15.2) is released. thanks for all the input :)
