### ISSUE TITLE
Is a protocol required for adding a port?

### ISSUE THREAD

**Issue by o5** [medialize/URI.js#232]
I'm not sure if it is a bug or not (and if it is possible), but first example bellow (marked `// 1`) returns a little bit unexpected result for me.

```js
// 1
var uri = require('URIjs')('127.0.0.1');
uri.port(8080);
console.log(uri.toString()); //prints "127.0.0.1" instead of expected "127.0.0.1:8080"

// 2 - if an input has protocol, it works fine
var uri = require('URIjs')('http://127.0.0.1');
uri.port(8080);
console.log(uri.toString()); //prints "http://127.0.0.1:8080/"
```

```
URIjs v1.15.1
Node v0.12.2
```

Thanks!

**Comment by rodneyrehm** [comment]
This is not a bug, this is expected behavior. The reason is that if the URL does not contain `//` as the protocol-authority-delimiter, the input is parsed as if it were a path. The [URL spec](http://url.spec.whatwg.org/) avoids this discussion by claiming `TypeError: 127.0.0.1 is not a valid URL`.

**Comment by o5** [comment]
I'll prepend `//` to input if protocol not set. Thanks for the suggestion.
