### ISSUE TITLE
Expose Data object from UriTemplate.js

### ISSUE THREAD

**Issue by XVincentX** [medialize/URI.js#234]
Hello!

I am in trouble using `UriTemplate` component from my application, since the `expand` method is using Data structure which is internal and not exposed, so I cannot create new instances of that.

If you have a look to the source [code](https://github.com/medialize/URI.js/blob/1a7326245bf8f4d465e80ad415bcf7b4ba9e479f/src/URITemplate.js#L142), you can notice that the function is accepting an instance of Data object, but I do not know to create a new one from external code

It is very easy issue to reproduce:
```coffeescript
UriTemplateComponent.expand expression, anything
```

**Comment by rodneyrehm** [comment]
I'm sorry, but I don't understand your problem. Why are you using `URITemplate.expand` (an internal function) at all? What internal data structure is the problem? all I see is [`operators`](https://github.com/medialize/URI.js/blob/1a7326245bf8f4d465e80ad415bcf7b4ba9e479f/src/URITemplate.js#L60). What are you trying to do here?

**Comment by rodneyrehm** [comment]
a month without following up on a question suggest there is no issue…
