### ISSUE TITLE
How to get query value?

### ISSUE THREAD

**Issue by xjchengo** [medialize/URI.js#235]
Currently, I use `URI.parseQuery((new URI()).query()).a` to get value of `a`. 
Is there any more semantic way like `(new URI()).getQuery('a')`?

**Comment by rodneyrehm** [comment]
there are [a couple of options](http://medialize.github.io/URI.js/docs.html#accessors-search), the one I'd go for is

```js
console.log( URI().query(true).a );
```

**Comment by xjchengo** [comment]
This is good. Thanks.
