### ISSUE TITLE
Pathname + Search

### ISSUE THREAD

**Issue by chiplay** [medialize/URI.js#237]
Is there a better way of outputting just the pathname + search from a `uri` object than `uri.path() + '?' + uri.query()`? I feel like i'm doing something wrong to have to compose that string manually.

**Comment by rodneyrehm** [comment]
If you have a look at [Components of an URI](http://medialize.github.io/URI.js/about-uris.html#components) you may find [.resource()](http://medialize.github.io/URI.js/docs.html#accessors-resource):

```js
URI('http://example.com/hello/world.html?foo=bar#blarp').clone().fragment('').resource();
// "/hello/world.html?foo=bar"
```

**Comment by chiplay** [comment]
@rodneyrehm thanks!
