### ISSUE TITLE
preview addSearch() href?

### ISSUE THREAD

**Issue by julegatti** [medialize/URI.js#239]
Is there a better way to preview how a uri would be if I add a search to the current URI without creating a new instance of its own?
I have this,

```
uri = new URI()

filters = {
    'device': uri.clone().addSearch('device', data.device).href(),
    'model': uri.clone().addSearch('model', data.model).href(),
    'version': uri.clone().addSearch('version', data.version).href()
}
```

The problem is that I have to do that inside a loop of about 200 elements, and I wonder about performance of creating multiple instances of URI lib.

**Comment by rodneyrehm** [comment]
> The problem is that I have to do that inside a loop of about 200 elements, and I wonder about performance of creating multiple instances of URI lib.

I don't think you can do anything differently. Except for using `uri.query(true)` once to get the current set and then pass the mutated object back to `.query()`. This would save you parsing the query string 200 times. not sure what kind of an answer you were expecting here

**Comment by julegatti** [comment]
Well, that's a good option. 
I was wondering if there was a function to just print the result of `uri.addSearch()` without modifying the `uri` instance.
