### ISSUE TITLE
removing query where it is no param name

### ISSUE THREAD

**Issue by kodentsev** [medialize/URI.js#243]
For example,
URI('http://hvgbook.net/?=5640').readable()===http://hvgbook.net/
URI('http://hvgbook.net/?=2500').readable()===http://hvgbook.net/

While it is 2 different pages.
Other methods (such as unicode()) lead to the same result.

**Comment by rodneyrehm** [comment]
according to [the url specification](https://html.spec.whatwg.org/multipage/forms.html#application/x-www-form-urlencoded-decoding-algorithm) that is considered legal, interesting.

are you up to fixing the issue and sending a pull request?

**Comment by kodentsev** [comment]
Yep, I've just done it

**Comment by rodneyrehm** [comment]
@kodentsev care to send your fix as a pull request against master?

**Comment by rodneyrehm** [comment]
ping @kodentsev

**Comment by rodneyrehm** [comment]
fixed in [1.19.2](https://github.com/medialize/URI.js/releases/tag/v1.19.2)
