### ISSUE TITLE
Mention that URI.js can be used by itself

### ISSUE THREAD

**Issue by deltab** [medialize/URI.js#249]
Although the website tells us to use the build.html page to compile the library, this didn't work for me (#184?). I decided to try downloading just the file [URI.js](https://github.com/medialize/URI.js/blob/gh-pages/src/URI.js) and found that it worked within my own page.

**Comment by rodneyrehm** [comment]
> Although the website tells us to use the build.html page to compile the library, this didn't work for me (#184?)

*how* did that not work for you? The build tool works fine in Firefox and Chrome…

The third paragraph on the [home page](https://medialize.github.io/URI.js/) says

> While URI.js provides a jQuery plugin. URI.js itself does not rely on jQuery. *You don't need jQuery* to use URI.js

The second paragraph on the [jQuery plugin page](https://medialize.github.io/URI.js/jquery-uri-plugin.html) says

> URI.js does not depend on jQuery unless you want to use the URI.js jQuery Plugin
