### ISSUE TITLE
removeQuery won't remove the last value of a variable if provided in an Array

### ISSUE THREAD

**Issue by Siltaar** [medialize/URI.js#256]
Hi,

To have easy interactions between json objects and Search/Query serialisation, I addQuery and removeQuery elements always providing a list. This works great except it removeQuery, not removing the last value of a multi-value GET variable, if this value is specified via a singleton list (which is not illegal).

I am to provide a pull request fixing this small issue.

**Comment by rodneyrehm** [comment]
I'm afraid I don't quite understand your problem. Please provide an example of how you use URI.js to illustrate what *is* happening and what you think *should* happen? something along the lines of:

```js
URI('?foo=bar&foo=bam&foo=bar').removeQuery('foo', 'bar').toString()
// "?foo=bam"

URI('?foo=bar&foo=bam&foo=bar').removeQuery('foo', ['bar', 'bam']).toString()
// ""
```

after we understand the problem and confirmed it is a bug, you're *welcome* to send a PR :)

**Comment by Siltaar** [comment]
Here it is.
Whatchout that I removed : ['bar'], then ['bam'].
Also, removing ['bar'] works, and removing ['bam'] don't, because its the last value.

URI('?foo=bar&foo=bam&foo=bar').removeQuery('foo', ['bar']).toString()
// "?foo=bam"

URI('?foo=bar&foo=bam&foo=bar').removeQuery('foo', ['bam']).toString()
// "?foo=bam"

**Comment by Siltaar** [comment]
The fix is simple (I wait your approval to provide it as a push-request) : 
---
 src/URI.js | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/URI.js b/src/URI.js
index 739f788..d9e0989 100644
--- a/src/URI.js
+++ b/src/URI.js
@@ -777,7 +777,7 @@
           } else {
             data[name] = filterArrayValues(data[name], value);
           }
-        } else if (data[name] === value) {
+        } else if (data[name] === value || (isArray(value) && data[name] === String(value[0])))
           data[name] = undefined;
         } else if (isArray(data[name])) {
           data[name] = filterArrayValues(data[name], value);

**Comment by Siltaar** [comment]
(diff syntax is not greatly supported here, and we're missing a '{' because of end-of-line cut in my tig utility…)

**Comment by rodneyrehm** [comment]
I'm afraid I still don't understand the problem regarding "because it's the last value", as I cannot find a way to reproduce that:

```js
URI('?foo=bar&foo=bam&foo=bar').removeQuery('foo', 'bar').toString();
// "?foo=bam"
URI('?foo=bar&foo=bam&foo=bar').removeQuery('foo', ['bar']).toString();
// "?foo=bam"

URI('?foo=bar&foo=bam&foo=bar').removeQuery('foo').toString();
// ""
URI('?foo=bar&foo=bam&foo=bar').removeQuery('foo', 'bar').removeQuery('foo', 'bam').toString();
// ""
URI('?foo=bar&foo=bam&foo=bar').removeQuery('foo', ['bar']).removeQuery('foo', ['bam']).toString();
// ""
URI('?foo=bar&foo=bam&foo=bar').removeQuery('foo', ['bar', 'bam']).toString();
// ""
```

Please provide a concrete code example to allow me to narrow this down

**Comment by Siltaar** [comment]
Sorry, I forgot to update the source string, my second example should have been : 

URI('foo=bam').removeQuery('foo', ['bam']).toString()
// "?foo=bam"

**Comment by Siltaar** [comment]
I have :
URI('?foo=bar&foo=bam&foo=bar').removeQuery('foo', ['bar']).removeQuery('foo', ['bam']).toString();
// "?foo=bam"

With URI.js Version: 1.16.1

**Comment by Siltaar** [comment]
You may understand based on the fix I suggest : https://github.com/Siltaar/URI.js/commit/3c999cd9e8c251b8eeac39b58b8b8c0a0edd6d0a

**Comment by Siltaar** [comment]
The problem occurs also for me with chromium 45.0.

I wonder how it could work for you without my patch, as you test on isArray(data[name]) (at line 782) ; which is false for the last value of a given "name" on "data" side.

**Comment by rodneyrehm** [comment]
> I wonder how it could work for you without my patch

I'm pretty sure it works for me, because I'm running the tests against master, which already includes #252. While targeting a different problem, it also "fixes" your problem.

This is the case, because `data[name] === value || (isArray(value) && data[name] === String(value[0]))` and `data[name] === String(value)` are equivalent for arrays containing exactly one element.

Looking at #252 now, I can see a problem coming up with comma separated values:

```js
URI('?foo=one&foo=two').removeQuery('foo', ['one', 'two']).toString()
// ""
URI('?foo=one,two').removeQuery('foo', ['one', 'two']).toString()
// "" <- this should not have happened
```

Following your defensive approach, I'd rewrite line 780 to

```js
 } else if (data[name] === String(value) && (!isArray(value) || value.length === 1)) {
```

in order to make sure `['one', 'two']` is not serialized to `one,two`.

You're welcome to make that change and send a PR for it. Please open the PR against the *master* branch and make sure to add a test covering the positive and negative effects.

**Comment by Siltaar** [comment]
Thanks a lot.
I will look forward to discover your test framework.

**Comment by rodneyrehm** [comment]
> I will look forward to discover your test framework.

Open `URI.js/test/test.URI.html`in your browser after you cloned the repo and checked out master. URI.js is using [QUnit](http://qunitjs.com/). The test module you're looking for is [removeQuery](https://github.com/medialize/URI.js/blob/master/test/test.js#L858-L892).

**Comment by Siltaar** [comment]
I committed 2 tests, coverings to cases about singleton list removeQuery.
It seems to me this represents the positive effects.
What could be a negative effect from your point of view (providing that validating all the other tests represents, for me, the covering of possible negative effect).

**Comment by rodneyrehm** [comment]
> I committed 2 tests, coverings to cases about singleton list removeQuery.

what do you mean by "singleton array"?

> What could be a negative effect from your point of view (providing that validating all the other tests represents, for me, the covering of possible negative effect).

I assumed you would fix line 780 like [suggested](https://github.com/medialize/URI.js/issues/256#issuecomment-147412803). A negative test is given in the same comment: 

```js
URI('?foo=one,two').removeQuery('foo', ['one', 'two']).toString()
// "" <- this should not have happened
```

so the test would be to make sure that the query doesn't change :)

**Comment by Siltaar** [comment]
> what do you mean by "singleton array"?

A singleton is an ensemble/set containing a single element. The word is used in math. and works the same in english and french :-)

> I assumed you would fix line 780 like suggested.

I just added 3 more tests, covering this example of negative effect you spotted. So I "remembered" the problem and added back the defensive approach on line 780 to comply new tests.

**Comment by rodneyrehm** [comment]
nice! can you squash the commits into a single one with the message `fix(removeQuery): prevent comma-serialization introduced by #252, closes #256`

**Comment by Siltaar** [comment]
Here it is.

**Comment by rodneyrehm** [comment]
Thank you very much! Do you need a new version published right away?

**Comment by Siltaar** [comment]
> Thank you very much! Do you need a new version published right away?

I'm not in a hurry, I'm using directly URI.js for the moment. I just need the tests to still pass for the future releases :-)

Thanks for your time, and all the explanations.
