### ISSUE TITLE
urijs requires that a uri has a protocol [v1.16.0]

### ISSUE THREAD

**Issue by Rdbaker** [medialize/URI.js#259]
I found that when I was testing if a URI was of a specific domain that it required that the URI had a protocol. If I left out the protocol, here's what the result looked like:

<img width="447" alt="screen shot 2015-10-17 at 3 24 40 pm" src="https://cloud.githubusercontent.com/assets/2810764/10560782/39b43c64-74e3-11e5-8dde-00f1e570eab7.png">

**Comment by rodneyrehm** [comment]
yes, that's known behavior - not a bug. see #232 or #187 for details
