### ISSUE TITLE
Easiest way to filter query parameters

### ISSUE THREAD

**Issue by justinmchase** [medialize/URI.js#262]
Suppose I want to remove all query parameters _except_ a few from a whitelist. Is there a one-line way to do this? Or what is the easiest way currently?

For example, I would like to:

```
var u = URI('http://example.com/foo?a=1&b=2&c=3');
u.filterQuery('a');
assert.equal('http://example.com/foo?a=1', u.toString());
```

**Comment by rodneyrehm** [comment]
There is no built-in way to filter the query data, but `.query()` accepts a callable that could be used for that. I guess best utility to filter the parsed query data object would be [`_.pick()`](http://underscorejs.org/#pick). For example:

```js
// using underscore
var filterQuery = function(data) {
  return _.pick(data, 'a');
};

// no underscore at hand
var filterQuery = function(data) {
  var _data = {};
  ['a'].forEach(function(key) {
    _data[key] = data[key];
  });
  return _data;
};

URI('http://example.com/foo?a=1&b=2&c=3').query(filterQuery).toString();
```

**Comment by justinmchase** [comment]
Ok, maybe I'll make another pull request I seem to be needing this a lot.

**Comment by rodneyrehm** [comment]
I'm not sure adding this to URI.js is a good idea. Different people tend to need different filters and that quickly blows up. You're filtering by property name, others may want to filter by value, or both. How about you add something along the following lines to your implementation to make this reusable for you?

```js
URI.filterQuery = function(parameterNames) {
  return function(data) {
    var _data = {};
    parameterNames.forEach(function(key) {
      _data[key] = data[key];
    });
    return _data;
  };
};

URI('http://example.com/foo?a=1&b=2&c=3')
  .query(URI.filterQuery(['a']))
  .toString();


URI('http://example.com/foo?a=1&b=2&c=3')
  .query(URI.filterQuery(['b', 'c']))
  .toString();
```
