### ISSUE TITLE
.equals() does not work for case sensitive system urls (e.g. about:tabs)

### ISSUE THREAD

**Issue by vitalets** [medialize/URI.js#265]
```js
new URI('about:tabs').equals('about:tabs') // true
new URI('about:tabs').equals('about:TABS') // false
```
the same with `about:blank`

**Comment by rodneyrehm** [comment]
`.equals()` only works its full charms on URLs, `about:tabs` is a URN, though. I don't see how we can make this work.

**Comment by vitalets** [comment]
Is it possible to compare such URNs just via `toLowerCase()` ?

**Comment by rodneyrehm** [comment]
> Is it possible to compare such URNs just via `toLowerCase()` ?

I expect that to depend on the protocol. we'd have to find a way to register protocol handlers to allow such things.
