### ISSUE TITLE
segment() and segmentCoded() behaviour seems inconsistent

### ISSUE THREAD

**Issue by mxgr7** [medialize/URI.js#266]
```
new URI("http://example.org/").segmentCoded("append this") 
// "http://example.org/add%20this"

new URI("http://example.org/").segment("append this") 
// "http://example.org/add%20this"
```
To me it seems logical that in the second line, the segment should not be encoded. So the resulting URI should be `"http://example.org/add this"`.

Otherwise, what way is there to build a URI with special but unescaped characters?

**Comment by rodneyrehm** [comment]
The difference becomes visible when dealing with encoded strings:

```js
URI("http://example.org/").segment("append%20this").toString()
// "http://example.org/append%20this"

URI("http://example.org/").segmentCoded("append%20this").toString()
// "http://example.org/append%2520this"
```

`.segment()` will decode and then encode (short: recode) the value, where `segmentCoded()` will only encode the value without decoding it first.

> Otherwise, what way is there to build a URI with special but unescaped characters?

It is recommended to escape everything you can. The built-in accessors will do that for you. If you don't want that, you need to work around them, e.g. by working with `.path()` directly.

**Comment by mxgr7** [comment]
Thanks for clearing that up.
> e.g. by working with .path() directly.

That doesn't work either, because in `.path()` the path gets recoded as well. I guess there is no way to enforce un-encoded path segments.

**Comment by rodneyrehm** [comment]
>  I guess there is no way to enforce un-encoded path segments.

I don't know why you'd need that - other than to mutate your URL in such a way that it is "interpreted properly" by some other system. Maybe that system should accept encoded data?

Anyway, you can access `._parts.path` to touch the internal store directly:

```js
var u = URI('http://example.com/foo/bar.html');
console.log(u._parts.path);
// "/foo/bar.html"

u._parts.path = '/unencoded space/world.gif';
console.log(u.toString());
// "http://example.com/unencoded space/world.gif"

// just don't normalize the url afterwars
console.log(u.normalize().toString());
// "http://example.com/unencoded%20space/world.gif"
```

**Comment by mxgr7** [comment]
> I don't know why you'd need that

I want to include parentheses in the path of some URIs, e.g. `http://example.com/foo(bar)`. To keep those more human readable, I would like to keep the parentheses unescaped.

**Comment by rodneyrehm** [comment]
> »Be conservative in what you do, be liberal in what you accept from others« -- [Postel's law](https://en.wikipedia.org/wiki/Robustness_principle)

For URI.js this means escaping everything, even if it is not deemed necessary. There's always a system that'll *not* cover *all* the edge cases.

Maybe [.readable()](http://medialize.github.io/URI.js/docs.html#readable) is what you're looking for?

**Comment by mxgr7** [comment]
Thanks again. Yes, [.readable()](http://medialize.github.io/URI.js/docs.html#readable) will fine do for my purposes.
