### ISSUE TITLE
equals() and canonical uris

### ISSUE THREAD

**Issue by jeromew** [medialize/URI.js#268]
Hello,

I understand that equals allows to detect when 2 uris reference the same resource, by allowing a different order of parameters.

For instance

    urijs('http://example.com?a=a&b=b').equals('http://example.com?b=b&a=a') => true

nevertheless, `normalize()` does not re-order parameter to a canonical order

    urijs('http://example.com?a=a&b=b').normalize() => 'http://example.com?a=a&b=b'
    urijs('http://example.com?b=ba=a').normalize() => 'http://example.com?b=b&a=a'

It there a way with urijs to get a `canonical` uri that would be the same for all uri that are `equals()`

I would like to store uris in a database and such a canonical representation would allow to use a unique string field to avoid pointing to duplicate ressources.

**Comment by ooxi** [comment]
I do not think that this is true in the general case since a web application *could* derive information from the parameter ordering.

That said, you could remove all arguments, sort them alphabetically and add them again in order to get a ordered representation.

**Comment by jeromew** [comment]
ok I agree that the ordering *could* have a meaning. On the same order of things, isn't the `equals` method opiniated in that it *could* consider equal uri pointing to different resources ?

I'll probably do as you suggest and try the remove/add dance.

thank you

**Comment by rodneyrehm** [comment]
> ok I agree that the ordering could have a meaning. On the same order of things, isn't the equals method opiniated in that it could consider equal uri pointing to different resources ?

As it stands right now, URI.js is *not* handling parameters in a location-safe way: #211, #173 (… and others). That said, I think your proposal would only worsen the situation.

> I'll probably do as you suggest and try the remove/add dance.

I don't think that dance is necessary:

```js

URI('?b=1&a=b&a=a').query(function(data) {
  var _data = {};
  Object.keys(data).sort().forEach(function(key) {
    if (Array.isArray(data[key])) {
      data[key].sort();
    }

    _data[key] = data[key];
  });
  return _data;
}).normalize().toString()
// "?a=a&a=b&b=1"
```

**Comment by jeromew** [comment]
Thanks for the solution with the query callback I had missed that part.

Indeed I understand that as of now `parseQuery` store the parameters as a bag of parameters so ordering or double-entries are hard to handle (I read the issues you mentioned).

the `qs` module does not handle the position of parameter either (https://github.com/hapijs/qs)

I could not find any query-string oriented module that handle the parameters as an order-preserving structure (they seem to all use an object bag)

So I guess that a location-aware query string handler will need to be implemented as a new module.

**Comment by rodneyrehm** [comment]
> I could not find any query-string oriented module that handle the parameters as an order-preserving structure (they seem to all use an object bag)

Most implementations I've come across do. But that hasn't kept developers from side-stepping those APIs and parse the QS themselves. URIs are a shit show :(

> So I guess that a location-aware query string handler will need to be implemented as a new module.

correct. Whenever we get around to v2… (crawling back under my rock now…)

**Comment by jeromew** [comment]
I agree that the show isn't the best of the shows ;-) 

I'll close this ticket for now (your solution works and I understand the overall issue).
Thanks for taking time to answer !
