### ISSUE TITLE
uri.search(true) is un-intuitive and confusing

### ISSUE THREAD

**Issue by bbusschots** [medialize/URI.js#271]
I just spent 30 minutes trying to figure out how to get the values for the parameters of the query string. I read and re-read the docs about 10 times before finally spotting the single line:

`uri.search(true); // returns { foo: "bar", hello : ["world", "mars"] }`

I passed search() and query() by three times because the docs said they were for returning the query string as a string with or without the ?. Having such important functionality hidden in a function that does something else, and accessed via a magic number is very confusing for users.  Passing true is just so meaningless and un-intiutive!

Magic numbers make for hard to read, and hence maintain, code.

I think an alias is needed so that users can write clearer code. I would suggest something like:

`uri.queryData()`, or `uri.searchData()`

At the very least I think the docs need to be tweaked so this magic number is much nearer the top of the description of the query and search functions.

This is commonly needed functionality, and I wasted a lot of time an energy trying to figure out what to do because of how un-intuitive the API is. I think a small tweak to make it more human-friendly would save a lot of people a lot of frustration in the futre.

**Comment by rodneyrehm** [comment]
You're welcome to send a PR to make the docs simpler to read :)

**Comment by josheinstein** [comment]
I guess I have only ever used the library to build URLs and not parse them, because I just beat my head against the wall over the same thing. I think it's because search/query feels inconsistent with other methods that double as setters and getters. I was expecting query("foo") to return "bar" since query("foo", "bar") sets it.

**Comment by rodneyrehm** [comment]
I'm the first to admit the query() method is an ugly beast. Sadly there's nothing we can do about this without breaking backward compatibility - so there's no quick solution.

Should I ever get around to actually starting work on version 2, the `.query` would be a separate - exchangeable - interface. Query strings are a world of their own…
