### ISSUE TITLE
Support RegExp for hasQuery name

### ISSUE THREAD

**Issue by mbrodala** [medialize/URI.js#274]
`URI.hasQuery` does not allow RegExp for parameter names like for values. The following would be a nice complement to the RegExp support in `URI.removeQuery`:

```
var uri = URI("http://example.org/?foo[bar]=1&foo[qux]=2");

uri.hasQuery(/^foo/); // true
uri.hasQuery(/^baz/); // false
```

**Comment by rodneyrehm** [comment]
feel free to send a PR for changing [URI.hasQuery](https://github.com/medialize/URI.js/blob/gh-pages/src/URI.js#L798-L810) and its [test](https://github.com/medialize/URI.js/blob/gh-pages/test/test.js#L987-L1047) accordingly

**Comment by mbrodala** [comment]
@rodneyrehm Should be straightforward, I'll give it a try.

**Comment by rodneyrehm** [comment]
thank you! :)
