### ISSUE TITLE
Regression in domain() method v.1.17.0

### ISSUE THREAD

**Issue by outaTiME** [medialize/URI.js#278]
Hi guys, 

In the latest URI.js version the domain() method doesn't work as expected ... take a look at this simple example:

version 1.16.1:

![screen shot 2016-02-20 at 1 05 29 pm](https://cloud.githubusercontent.com/assets/140472/13197642/a94daa2c-d7d2-11e5-9c47-35e851bff408.png)

version 1.17.0:

![screen shot 2016-02-20 at 1 06 02 pm](https://cloud.githubusercontent.com/assets/140472/13197643/b7d368ca-d7d2-11e5-8544-0948eb071f81.png)

thks !!

**Comment by rodneyrehm** [comment]
is it possible you loaded SecondLevelDomains.js in the 1.16.1 context, but not in the 1.17.0 context?

```js
URI('://hello.world.example.co.uk').is('SLD')
// true
URI('://hello.world.example.co.uk').domain();
// "example.co.uk"
URI.version
// "1.17.0"
```

**Comment by outaTiME** [comment]
Yay you are right, my bad ... 

thks !!!
