### ISSUE TITLE
Source still references GPL

### ISSUE THREAD

**Issue by justhamade** [medialize/URI.js#279]
We may run into issues using this library because GPL is still referenced in the source here
https://github.com/medialize/URI.js/blob/gh-pages/src/URI.js#L11

**Comment by rodneyrehm** [comment]
we [dropped GPL](https://github.com/medialize/URI.js#license) a while ago. Even though the comment still references GPL, it is the MIT license that applies.

**Comment by rodneyrehm** [comment]
last traces of GPL removed in [1.17.1](https://github.com/medialize/URI.js/releases/tag/v1.17.1)
