### ISSUE TITLE
ending `/` in uri.protocol()

### ISSUE THREAD

**Issue by acklavidian** [medialize/URI.js#281]
```js
//Enforce http on a URL.
function enforceHttps(url) {
    var url = new URI(url);

    //allow http if specified, but
    //if your first 4 letters that are not http then add https
    if (url.protocol() === "") {
        url.protocol("https");
    }
    return url.toString();
}
````
in this code block if I hit the if statement as true and the url.protocol("") setter is called then it returns a URL with a `/` at the end otherwise it does not have the `/` at the end. This seems weird to me and is making my tests fail. Any advice. Perhaps there is something else I should be doing. I need this function to basically add a https to a URL with no protocol, but if it does have a protocol just leave the existing protocol.

**Comment by acklavidian** [comment]
This fiddle illustrates the issue I am referring to: 
https://jsfiddle.net/98wzjw5u/3/

**Comment by rodneyrehm** [comment]
You assume that `new URI("example.org")` is parsed as a domain, when in fact this is a path.

```js
new URI("example.com").domain()
// ""
new URI("example.com").path()
// "example.com"

new URI("://example.com").domain()
// "example.com"
new URI("://example.com").path()
// "/"
```

So if you provide a scheme relative URL (e.g. `://example.org`), you'll always get the slash appended.

Also note that your fiddle converts all protocols to 'HTTP', unless no protocol is given, then it's `HTTPS`.

**Comment by acklavidian** [comment]
So is the `://` the only way to force it to be interpreted as a domain?

**Comment by mshwery** [comment]
Ah, so this only occurs on urls _without a path_. E.g. 

```js
new URI('http://example.com').toString();
// "http://example.com/"

new URI('http://example.com/foo').toString();
// "http://example.com/foo"
```

**Comment by acklavidian** [comment]
OOOh I see. That does make sense
