### ISSUE TITLE
addSearch() removes parameters when they are the same

### ISSUE THREAD

**Issue by pieterjandesmedt** [medialize/URI.js#282]
For an interface I'm creating, I need to send coordinates. For a closed polygon, first and last coordinates are the same. When I use 
```javascript
.addSearch({
	point: req.query.coords.split('|')
})
```
then `addSearch` seems to drop the last coordinate.

Example input:
```
req.query = { coords: '51.2235391,3.54101890000004|50.90130070888041,3.18603515625|50.848440021829276,4.36981201171875|51.2235391,3.54101890000004' }
```

after `addSearch`:
```
?point=51.2235391,3.54101890000004&point=50.90130070888041,3.18603515625&point=50.848440021829276,4.36981201171875
```

**Comment by rodneyrehm** [comment]
Have a look at `URI.duplicateQueryParameters = true;` or `URI().duplicateQueryParameters(true)` as explained in [`.buildQuery()`](http://medialize.github.io/URI.js/docs.html#static-buildQuery)

**Comment by pieterjandesmedt** [comment]
Thanks Rod for your quick reply. Works like a charm!
