### ISSUE TITLE
How to get segment X to end of URI?

### ISSUE THREAD

**Issue by dukedougal** [medialize/URI.js#283]
Given this URL:

'https://www.example.org/foozle/flibble/razz/base/files.json'

My goal is to get the fourth segment from the right (flibble), but return the entire URL from that position

So I understand uri.segment(-4); would locate that segment, but how can I get it to return not just that segment but everything from that point, i.e flibble/razz/base/files.json

thanks and loving urijs

**Comment by rodneyrehm** [comment]
> My goal is to get the fourth segment from the right (flibble), but return the entire URL from that position

If you need a relative URL, you may want to try

```js
var uri = URI('https://www.example.org/foozle/flibble/razz/base/files.json');
uri.relativeTo('https://www.example.org/foozle/').resource()
// result: "flibble/razz/base/files.json"
```

Another way would be to simply throw away the first directory of the path:

```js
var uri = URI('https://www.example.org/foozle/flibble/razz/base/files.json');
// get the path as array
var segments = uri.segment();
// remove the first element
segments.shift();
// set the path from array
uri.segment(segments);
// return URL without authority
uri.resource()
// result: "/flibble/razz/base/files.json"
```
