### ISSUE TITLE
import urijs into es6 project

### ISSUE THREAD

**Issue by helt** [medialize/URI.js#288]
I have to work with a ES6 project, and sought to use urijs for url manipulation. However, i do not seem to get urijs to be accepted in my source.

Neither `import URI from "urijs";` nor `import * as URI from "urijs";` nor plain `var URI = require("urijs");`
 will work out as imagined...

Maybe urijs is not compatible with es6 / babel or am i missing something obvious?

**Comment by helt** [comment]
Okay. I got it. 
```
import * as URI from 'urijs';
```

does work, but one thing -- namely the `URI()` function -- is not available...

**Comment by rodneyrehm** [comment]
I don't know what system you're using to import modules `import URI from 'urijs';` *should* work. That module has only one export and that should be considered the default export.

**Comment by helt** [comment]
argh. Invalidating intellij cache and restarting did the trick...

**Comment by athrunsun** [comment]
@rodneyrehm @helt 
Does `import URI from 'urljs';` really works when working with webpack?

If I write `const uri = new URI(SERVER_ADDR).path(urlPath);`, I get:
```
Unhandled Rejection (TypeError): __WEBPACK_IMPORTED_MODULE_0_urljs___default.a is not a constructor
```

If I write `const uri = URI(SERVER_ADDR).path(urlPath);`, I get:
```
Unhandled Rejection (TypeError): __WEBPACK_IMPORTED_MODULE_0_urljs___default(...) is not a function
```
