### ISSUE TITLE
Is there a way to disable auto encoding?

### ISSUE THREAD

**Issue by acklavidian** [medialize/URI.js#291]
Is there a way to disable auto % encoding?

**Comment by rodneyrehm** [comment]
In which component? for which purpose?

**Comment by acklavidian** [comment]
so our system uses flags that look like `[%code%]` in the query string. It resolves those placeholder values before passing this on to the client with additional queries generate by users.  Some users have queries stored with encoded special characters. In the past I had been using `.decode` to solve this issue. I didn't consider that we sometimes store encoded queries from users. Decode decodes the whole query, and I only need to ensure that the `[%code%]`/ (internal) parts as well as the user entered queries stay intact. Our system isn't concerned with encoding urls what so ever and I was wondering if there was a way to disable this feature as it seems to do this by default.

**Comment by rodneyrehm** [comment]
Do you have some code showing what you're doing / what you expect to be doing? Possibly with some dummy data?

**Comment by acklavidian** [comment]
I'll have to put something together.

**Comment by casertap** [comment]
Same thing here I am working with solr.
I am constructing part of the url like such
```
  const path = new URI('')
              .directory('/solr/restaurants')
              .filename('select')
              .addSearch('q=*:*&facet=true&facet.mincount=1&facet.field={!ex=tagForState}state&facet.field={!ex=tagForCity}city&facet.query={!ex=tagForPrice}price:[*%20TO%205}&facet.query={!ex=tagForPrice}price:[5%20TO%2010}&facet.query={!ex=tagForPrice}price:[10%20TO%2020}&facet.query={!ex=tagForPrice}price:[20%20TO%2050}&facet.query={!ex=tagForPrice}price:[50%20TO%20*]&fq={!tag="tagForState"}state:California')
              .addSearch('wt=json');

const uri = new URI('http://192.168.99.100:8980' + path);
console.log(`formatUrl2: ${uri}`);

````
I get this result:
```
http://192.168.99.100:8980/solr/restaurants/select?q%3D%2A%3A%2A%26facet%3Dtrue%26facet.mincount%3D1%26facet.field%3D%7B%21ex%3DtagForState%7Dstate%26facet.field%3D%7B%21ex%3DtagForCity%7Dcity%26facet.query%3D%7B%21ex%3DtagForPrice%7Dprice%3A%5B%2A%2520TO%25205%7D%26facet.query%3D%7B%21ex%3DtagForPrice%7Dprice%3A%5B5%2520TO%252010%7D%26facet.query%3D%7B%21ex%3DtagForPrice%7Dprice%3A%5B10%2520TO%252020%7D%26facet.query%3D%7B%21ex%3DtagForPrice%7Dprice%3A%5B20%2520TO%252050%7D%26facet.query%3D%7B%21ex%3DtagForPrice%7Dprice%3A%5B50%2520TO%2520%2A%5D%26fq%3D%7B%21tag%3D%22tagForState%22%7Dstate%3ACalifornia&wt%3Djson
```
but solr is not expecting this value and return an empty response.

The same request not encoded give me a good response
```
http://192.168.99.100:8980/solr/restaurants/select?q=*:*&wt=json&facet=true%E2%80%A6:[20%20TO%2050}&facet.query={!ex=tagForPrice}price:[50%20TO%20*]&fq={!tag=%22tagForState%22}state:California
```

**Comment by casertap** [comment]
I could do 
```
URI.decode(uri)
```
but it would have been better if it hadn't been encoded in the first place
adding a ```.encode(false)```

**Comment by rodneyrehm** [comment]
@casertap addQuery() assumes the second argument to be *one* value. Your example should work fine if you use [`.search()`](http://medialize.github.io/URI.js/docs.html#accessors-search) instead of [`.addSearch`](http://medialize.github.io/URI.js/docs.html#search-add) for setting that first big chunk of query data.

**Comment by casertap** [comment]
That is right, this solved the problem.
````
  const uri = new uri('')
              .directory('/solr/restaurants')
              .filename('select')
              .addsearch('q=*:*')
              .addsearch('facet=true')
              .addsearch('facet.mincount=1')
              .addsearch('facet.field={!ex=tagforstate}state')
              .addsearch('facet.field={!ex=tagforcity}city')
              .addsearch('facet.query={!ex=tagforprice}price:[*%20to%205}')
              .addsearch('facet.query={!ex=tagforprice}price:[5%20to%2010}')
              .addsearch('facet.query={!ex=tagforprice}price:[10%20to%2020}')
              .addsearch('facet.query={!ex=tagforprice}price:[20%20to%2050}')
              .addsearch('facet.query={!ex=tagforprice}price:[50%20to%20*]')
              .addsearch('fq={!tag="tagforstate"}state:california')
              .addsearch('wt=json');

```

**Comment by acklavidian** [comment]
I was just about to start working on this again! 👍

**Comment by casertap** [comment]
actually I still need to do ```URI.decode(path)``` when creating the URI how I describe before but this is fine.
