### ISSUE TITLE
Support userinfo with empty username but non-empty password

### ISSUE THREAD

**Issue by mika-fischer** [medialize/URI.js#292]
URIs like `foo://:pwd@host` are parsed correctly, i.e. `_parts` contains the correct info. But both `userinfo()` and `toString()` first check if username is set and ignore the password if username is empty.

**Comment by rodneyrehm** [comment]
Neither [3.2.1.  User Information](https://tools.ietf.org/html/rfc3986#section-3.2.1) nor the ABNF (below) indicates the username requirement, so this is a bug.

```abnf
userinfo      = *( unreserved / pct-encoded / sub-delims / ":" )
```
The entire `<username>:<password>` scheme seems to be an unspecified semantic, even though [7.5.  Sensitive Information](https://tools.ietf.org/html/rfc3986#section-7.5) is warning not to expose secret data in URLs.

Anyway, to fix your particular issue you'll want to look at [URI.buildUserinfo()](https://github.com/medialize/URI.js/blob/gh-pages/src/URI.js#L683-L697) and its [test](https://github.com/medialize/URI.js/blob/gh-pages/test/test.js#L403-L420). PR welcome :)
