### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by tlaak** [medialize/URI.js#295]
I'm trying to include the jQuery plugin in my code using ES6 modules, but URI in the plugin itself is undefined, thus the error on line 155 in jquery.URI.js. I'm using npm to install dependencies and the installed version is 1.18.

This is how I'm importing it in my code as I need both URI and the jQuery selectors.

```
import URI from 'urijs';
import 'urijs/src/jquery.URI';
```

Am I doing something wrong here?

**Comment by rodneyrehm** [comment]
I'm not sure how you resolve packages, so I can't say why this isn't working.

**Comment by tlaak** [comment]
In jquery.URI.js on line 19 there's `module.exports = factory(require('jquery', './URI'));` which is causing this issue.

It should probably be `module.exports = factory(require('jquery'), require('./URI'));`

**Comment by rodneyrehm** [comment]
wah! thanks for finding this. fixed in master.

**Comment by tlaak** [comment]
Wow that was fast! Thanks! 👍
