### ISSUE TITLE
UriTemplate needs to be defined globally

### ISSUE THREAD

**Issue by atrauzzi** [medialize/URI.js#297]
I'm using urijs from a module, but unfortunately I'm having to do this in order to make use of `URI.expand`:

```
window.URITemplate = UriTemplate;
```

Perhaps there's a better way to do this so that `URI` itself can import the functionality without me having to throw it into the global scope?

**Comment by rodneyrehm** [comment]
I'm not sure I understand why it would be necessary to expose window.URITemplate. [URI.expand](https://github.com/medialize/URI.js/blob/gh-pages/src/URITemplate.js#L505-L510) should be fine?!

**Comment by atrauzzi** [comment]
URI.expand only works for me *after* I've imported UriTemplate.  The issue is that URI has a function in it that won't work until you've put a dependency in the global scope.

URI should be including that dependency itself and not requiring me to put it on the `window` object.

**Comment by rodneyrehm** [comment]
> URI.expand only works for me after I've imported UriTemplate. 

The function `URI.expand()` is defined in `URITemplate.js` not in `URI.js`. This is expected.

> The issue is that URI has a function in it that won't work until you've put a dependency in the global scope.

I fail to see how [`URI.expand()`](https://github.com/medialize/URI.js/blob/gh-pages/src/URITemplate.js#L505-L510) could possibly benefit from putting someting on the `window` object.

> URI should be including that dependency itself and not requiring me to put it on the window object.

It is not requiring you to put anything on `window` as shown [here](https://github.com/medialize/URI.js/tree/master#nodejs-and-npm).

**Comment by atrauzzi** [comment]
Your explanations aren't necessarily negating what I'm saying.

I say `.expand` doesn't work unless I include `URITemplate.js`, you say "The function `URI.expand()` is defined in `URITemplate.js`".  I'm not disagreeing with this.

The issue is that you have to import `URITemplate.js` into the global scope.  And at least as far as modules go, this isn't great for conventions.

---

You even have a comment explaining that _"...root is window...":
https://github.com/medialize/URI.js/blob/gh-pages/src/URI.js#L24

And there is a check against it here:
https://github.com/medialize/URI.js/blob/gh-pages/src/URI.js#L1002

This might be more telltale? :
https://github.com/medialize/URI.js/blob/01cc0295f6bd61a509bd75fa3fc2ec1155607a78/src/URITemplate.js#L25

---

I'm not a total expert on JS packages, but I can tell you that I'm using TypeScript, and I'm not sure what it exposes to make it apparent that I'm doing module imports.  Perhaps some of the detections going on here aren't quite compatible with it, or need to be improved?  Other third party modules that I'm using don't seem to require that they put things on the window object.

That much I can prove and is repeatable in my setup here.  So something is definitely amiss.

**Comment by rodneyrehm** [comment]
> The issue is that you have to import URITemplate.js into the global scope. 

This is simply not true. 2 of the lines you reference are part of the UMD module definition. The third one is `.noConflict()` which simply proxies the the call through to URITemplate. As noConflict only makes sense in the world of browser globals, this is fine.

I guess you're confused about having to *load* the URITemplate module, and *exposing* it globally. 

> And at least as far as modules go, this isn't great for conventions.

As far as I know there is no convention for "optional modules". That doesn't mean that the current state of things is the best we can do. I'm open to suggestions…

**Comment by kavika13** [comment]
I hope I'm not completely off-thread in this comment, but here's my two cents:

> I guess you're confused about having to load the URITemplate module, and exposing it globally.

I ran into a problem just now where I imported the URI module and expected URITemplate to show up, and `URI.expand` to work. After an hour or so of googling, digging through issues on brunch.io, peeking at my concatenated source, and comparing it to URI.js github, etc, I finally figured out that I had to pull in `urijs/src/URITemplate.js` as well.

Adding more explicit instructions on this optional include on `index.html`, `docs.html`, and `uri-template.html` might save people some time in the future.

**Comment by rodneyrehm** [comment]
> Adding more explicit instructions on this optional include on `index.html`, `docs.html`, and `uri-template.html` might save people some time in the future. 

@kavika13 You're welcome to submit a PR for this.

**Comment by kavika13** [comment]
@rodneyrehm Thanks, I might do that.

I assessed a bit more of the scope just now, and finally got around to reading [the README](https://github.com/medialize/URI.js/blob/gh-pages/README.md). It has the some of the missing info I was searching for. Getting some of that into the HTML docs (even if just by a link) seems useful. If I end up submitting a PR for this, it will likely be in a few weeks to a month.
