### ISSUE TITLE
hasQuery doesn't work with array parameters

### ISSUE THREAD

**Issue by Kreshnik** [medialize/URI.js#301]
Hi,

There seems to be an issue with the hasQuery method, when you try to read array parameters i.e `name[]=first&name[]=second` the callback function value parameter returns `undefined` even though the values exist.

I had to use this solution as work around [StackOverflow](http://stackoverflow.com/a/15866004/1551070)

Would be nice to have this solved within the library itself.

**Comment by rodneyrehm** [comment]
Do you mind posting the code you'd expect to be able to write in this particular case?

**Comment by Kreshnik** [comment]
Yes of course, the code is as follow; 

```
uri.hasQuery('features', function (value, name, data) {
console.log(value)
}.bind(this));
```
features in the above case is an param array features[].

**Comment by rodneyrehm** [comment]
I see. You expect `[]` to not be part of the paramter's name. If you run `uri.hasQuery('features[]', …)` you'll get the data you want.

**Comment by Kreshnik** [comment]
It indeed works, thank you!
