### ISSUE TITLE
jquery-1.11.3.min.js:2 Uncaught Error: Syntax error, unrecognized expression: #!/category/6'

### ISSUE THREAD

**Issue by MubashirKP** [medialize/URI.js#302]
when i try to click on an anchor tag with href "//example.com/#!category/6", jquery throws this error in the console and the browser url doesnt change.
Why is this so ? is there a work around ?

:)

jquery-1.11.3.min.js:2 Uncaught Error: Syntax error, unrecognized expression: #!/category/6'ga.error @ jquery-1.11.3.min.js:2

ga.tokenize @ jquery-1.11.3.min.js:2
ga.select @ jquery-1.11.3.min.js:2
ga @ jquery-1.11.3.min.js:2
m.fn.extend.find @ jquery-1.11.3.min.js:2
m.fn.init @ jquery-1.11.3.min.js:2
m @ jquery-1.11.3.min.js:2
b @ bootstrap.min.js:6
(anonymous function) @ bootstrap.min.js:6
m.event.dispatch @ jquery-1.11.3.min.js:4
r.handle @ jquery-1.11.3.min.js:4

**Comment by rodneyrehm** [comment]
I don't see anything URI.js related in that stack trace. Maybe you want to start by finding out what `ga.tokenize` is?
