### ISSUE TITLE
normalize confusion

### ISSUE THREAD

**Issue by ezra-quemuel** [medialize/URI.js#304]
The doc says:

<h3>URI.unicode()<h3>

URI.unicode() restores the default unicode-encoded URLs.

```javascript
URI.unicode();

var uri = new URI("http://example.org/foo/æ.html");
// http://example.org/foo/%C3%A6.html
```

Therefore, I was expecting that calling ```javascript uri.toString()``` would result in *http://example.org/foo/%C3%A6.html*

However, it results in the original *http://example.org/foo/æ.html*

Shouldn't it call normalize in build? (it only seems to normalize the authority parts) or at least add a parameter to toString/valueOf that automatically normalizes?

I can also see some use cases where the consumer might not want to normalize, but I think this:
```javascript
new URI("http://example.org/foo/æ.html").toString(true) === "http://example.org/foo/%C3%A6.html";
```
is slightly cleaner than
```javascript
new URI("http://example.org/foo/æ.html").normalize().toString() === "http://example.org/foo/%C3%A6.html";
```

I can create a PR if this sounds like a good idea

**Comment by rodneyrehm** [comment]
> Shouldn't it call normalize in build?

`URI.build()` does *not* run `.normalize()` internally, but certain mutations do (`.filename()`, `.readable()`, `.absoluteTo()`, `relativeTo()`, `.equals()`, `.unicode()`, `.iso8859()` and `URI.joinPaths()`).

Maybe some code helps:

```js
URI("http://example.org/foo/æ.html").unicode().toString();
// "http://example.org/foo/%C3%A6.html"

URI.unicode();
URI("http://example.org/foo/æ.html").normalize().toString();
// "http://example.org/foo/%C3%A6.html"

URI.iso8859();
URI("http://example.org/foo/æ.html").unicode().toString();
// "http://example.org/foo/%C3%A6.html"
URI("http://example.org/foo/æ.html").toString();
// "http://example.org/foo/æ.html" (we're in ISO8859 mode)
```

---

Regarding the comparison of URLs I suggest you use [`.equals()`](http://medialize.github.io/URI.js/docs.html#equals), as that's what it's made for:

```js
// instead of
URI("http://example.org/foo/æ.html").normalize().toString() === "http://example.org/foo/%C3%A6.html";
// true

// use this
URI("http://example.org/foo/æ.html").equals("http://example.org/foo/%C3%A6.html");
// true
```

**Comment by ezra-quemuel** [comment]
So my use case is not for checking equality, but rather to save into a db.
The problem for me is that using .toString() without first using .normalize(), .unicode(), or .iso8859() will cause it to fail uri validation when it's not encoded.

I was merely suggesting a shortcut boolean parameter to be added toString() (or encode the string by default), so that the string it produces is a valid uri.

But again, it's just a suggestion (and maybe a bad one, but just thought to put that out there).

**Comment by rodneyrehm** [comment]
[`Object.prototype.toString()`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/toString) doesn't have arguments, so it wouldn't be a very good idea to add them here. But even if that weren't the case, [nobody would understand the meaning of that `true`](https://ariya.io/2011/08/hall-of-api-shame-boolean-trap) without consulting the docs. `URI('…').normalize().toString()` may be more to type, but it's definitely easier to understand.

Running `.normalize()` on every `.toString()` is a bad idea performance-wise. That's why they're separate functions.

Sorry…
