### ISSUE TITLE
Question: How to run tests?

### ISSUE THREAD

**Issue by amilajack** [medialize/URI.js#306]
How would i run the tests for this project?

**Comment by rodneyrehm** [comment]
run `npm install`, then open [test/index.html](https://github.com/medialize/URI.js/blob/gh-pages/test/index.html) in a browser.

**Comment by amilajack** [comment]
I see. So the tests are not automated?

**Comment by rodneyrehm** [comment]
> So the tests are not automated? 

You have to *trigger* running the tests manually. But you don't have to execute each test manually. So is that "automated" or not?

> Is there a way to run them in a CI service?

There are a number of ways to run qunit tests in CI, yes. I've never bothered to set that up for the current system, though. If I did, I'd likely try switching over to [AVA](https://github.com/avajs/ava) if running tests only in node was enough, or go with [Intern](http://theintern.github.io/) if I needed to run tests in actual browsers.

Are you interested in making this happen, or why were you asking?

**Comment by amilajack** [comment]
I was thinking of making a PR for this. Is that fine?

**Comment by rodneyrehm** [comment]
sure :)

what exactly were you planning on doing? and what are you hoping to accomplish by doing it?

**Comment by amilajack** [comment]
I wanted to ensure its coverage
