### ISSUE TITLE
Long array parsing

### ISSUE THREAD

**Issue by j-noah-potter** [medialize/URI.js#308]
Is there a reason that

`URI().search({a: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}).search(true)`

returns `a` as an object and

`URI().search({a: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}).search(true)`

returns `a` as an array?

21 elements seems to be the cutoff but I can't find that number in the source. Is it a regex thing?

**Comment by rodneyrehm** [comment]
I get `{a: "1"}` in both cases.

You *can* make URI.js *not* collapse duplicate values by setting `duplicateQueryParameters` (either globally using `URI.duplicateQueryParameters = true`, or per instance using `URI().duplicateQueryParameters(true)`):

```js
URI().duplicateQueryParameters(false).search({a: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}).search(true)
// {"a":"1"}

URI().duplicateQueryParameters(true).search({a: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}).search(true)
// {"a":["1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"]}
```

**Comment by j-noah-potter** [comment]
Sorry for the trouble. I had replaced the parser with qs. Thanks for the help.
