### ISSUE TITLE
Searching relative paths with .withinString

### ISSUE THREAD

**Issue by sahanarula** [medialize/URI.js#309]
Currently withinString doesn't search for relative paths. Any way to do that?

**Comment by rodneyrehm** [comment]
Well, you could have a look at extending [`.withinString`](https://github.com/medialize/URI.js/blob/gh-pages/src/URI.js#L940-L977) accordingly. [`URI.findUri.start`](https://github.com/medialize/URI.js/blob/gh-pages/src/URI.js#L217-L224) may be of particular interest. There are some [tests](https://github.com/medialize/URI.js/blob/gh-pages/test/test.js#L1571-L1621) you'd want to extend.

**Comment by sahanarula** [comment]
Thanks @rodneyrehm It helped.

**Comment by rodneyrehm** [comment]
Is this a feature URI.js needs to provide for everyone? If not, could you post your solution here, so that if someone else needs the same thing, they have a starting point?
