### ISSUE TITLE
Get query string parameter value?

### ISSUE THREAD

**Issue by tylercollier** [medialize/URI.js#31]
With URI.js, it's easy to SET parameters.

I've read all the docs and hope I'm missing something, but I can't find a good way to GET the query string parameter value.

What I'm having to do now is this:

``` javascript
if (url.search(true).hasOwnProperty("my_parameter_name")) {
  console.log("parameter value is" + url.search(true).my_parameter_name);
}
```

Is there a better way?

**Comment by blueguy9192** [comment]
I agree with schmijos and  slisznia . At the least the doc should have an example of getting a specific query parm value. This : 

uri.search(true); // returns { foo: "bar", hello : ["world", "mars"] }

doesn't help the newbie javascript programmer enough. I'd prefer a single getter function, even if it is inefficient. The doc could note that fact and possibly explain a better method so then the programmer can decide if they care about the inefficiency.

**Comment by rrauenza** [comment]
I'm in the position where I want to get only the first value from the query string (in case someone has munged up the query string manually).

Right now I have to do:

    q = uri.search(true);
    res = q['foo']
    if (Array.isArray(res)) { return res[0] } else { return res['foo'] }

....if an API is created for grabbing a specific key, adding the ability to only grab the first one might be useful?

**Comment by krowe-hsc** [comment]
The getter method is only less efficient if you want to read more than one query string parameter. When you consider that most sites are already hiding many parameters in the path and hostname using rewrite rules, this is actually going to be a lot more common scenario than it may at first seem.

**Comment by aandis** [comment]
With `1.15.1`, I found this to be concise enough - 
```javascript
if (url.hasQuery("my_param")) {
  var value = url.query(true).my_param;
}
```
