### ISSUE TITLE
Downloaded build (made with closure compiler) incompatible with RequireJS

### ISSUE THREAD

**Issue by pmorch** [medialize/URI.js#310]
I went to [URI.js - Custom Build](https://medialize.github.io/URI.js/build.html) and built some text that I saved to a `URI.js` file. It doesn't work with RequireJS with

```javascript
var config = {
   "paths" : {
      "URI" : "/path/to/URI",
    }
};
require.config( config );
require(['/path/to/URI'], function(URI) { new URI("http://www.morch.com") })
```

The first time I get a `TypeError: URI is not a constructor` error and the next time I get a `Error: Mismatched anonymous define() module` error.

If I use the `git clone` source or use RequireJS's `r.js` to minify said source it works fine, so it seems there isn't anything wrong with neither URI.js or my use of RequireJS, only that the build process does not yield a result that is compatible with RequireJS.

Fixing the build to be RequireJS compatible and/or a note on the build page would've been nice. 

I'm not sure if this is related to #118  or #147 but this sounds like a different issue - about the closure-compiler-based build.

And to build a RequireJS compatible `URI.min.js`  is really easy:
```
londo@peter:~/build> git clone git@github.com:medialize/URI.js.git 
Cloning into 'URI.js'...
remote: Counting objects: 4772, done.
remote: Total 4772 (delta 0), reused 0 (delta 0), pack-reused 4772
Receiving objects: 100% (4772/4772), 2.21 MiB | 2.67 MiB/s, done.
Resolving deltas: 100% (2945/2945), done.
Checking connectivity... done.

londo@peter:~/build> cd URI.js/

londo@peter:~/build/URI.js> npm install requirejs
requirejs@2.2.0 node_modules/requirejs

londo@peter:~/build/URI.js> ./node_modules/.bin/r.js -o baseUrl=./src  name=URI out=URI.min.js

Tracing dependencies for: URI
Uglify file: /home/peter/build/URI.js/URI.min.js

/home/peter/build/URI.js/URI.min.js
----------------
/home/peter/build/URI.js/src/punycode.js
/home/peter/build/URI.js/src/IPv6.js
/home/peter/build/URI.js/src/SecondLevelDomains.js
/home/peter/build/URI.js/src/URI.js

londo@peter:~/build/URI.js> ls -l URI.min.js 
-rw-r--r-- 1 peter peter 41399 Aug 24 20:54 URI.min.js
```

This one works

**Comment by rodneyrehm** [comment]
Thanks for pointing this out. The "build tool" will show a warning with the next update of the site.
