### ISSUE TITLE
Slash isn't added automaticaly to the end of an origin

### ISSUE THREAD

**Issue by iseeyou911** [medialize/URI.js#313]
Case:
At first create an instance of URI with only domain (without protocol), and set the protocol after:
```
const uri1 = new URI('test.com').protocol('http');
```
Then create an instance of `URI` with `uri1` as constructor arg:
```
new URI(arg1).toString()
>>"http://test.com"
```
And slash was not added.

But if create the instance with `uri1.toString()` as constructor arg, everything is fine:
```
new URI(uri1.toString()).toString()
>>"http://test.com/"
```

Expected:
```
new URI(uri1).toString()
>>"http://test.com/"
```

**Comment by rodneyrehm** [comment]
The problem is rooted in the assumption that `URI('test.com')` would be parsed as a domain. It is not. It is a path. You can verify this my by running `URI('test.com').domain()` and `URI('test.com').path()`.

**Comment by iseeyou911** [comment]
ok. tnx for explaining.
