### ISSUE TITLE
Segment method doesn't seem to accept integers

### ISSUE THREAD

**Issue by mattmanske** [medialize/URI.js#315]
Passing an integer to the `.segment()` method doesn't work as expected. It does work however if I change the integer to a string before passing it through. 

Maybe this is a design choice, but it does seem to be unexpected behavior and doesn't fail in a descriptive way.

https://jsfiddle.net/k6advmLq/

**Comment by rodneyrehm** [comment]
> Maybe this is a design choice, but it does seem to be unexpected behavior and doesn't fail in a descriptive way.

the docs for [`.segment()`](http://medialize.github.io/URI.js/docs.html#accessors-segment) show that for the first argument numeric values are considered indices for getting or setting values. String values are *appended* as a new segment.
