### ISSUE TITLE
addSearch does not add query params to end of url

### ISSUE THREAD

**Issue by vincent89** [medialize/URI.js#320]
I have the following code:
var uri = new URI('https://debug.test.com/#/accept');
uri.addSearch({ param: "a" })

Which turns the uri into https://debug.test.com/?param=a#/accept
While I need it to be https://debug.test.com/#/accept?param=a

Am I using the librairy wrong or is this an issue?

**Comment by rodneyrehm** [comment]
> Am I using the librairy wrong or is this an issue?

Have a look at [URI components](http://medialize.github.io/URI.js/about-uris.html#components) to undertand the difference between the query string (also called *search*) and the fragment (also called *hash*).

> While I need it to be https://debug.test.com/#/accept?param=a

Have a look at [Working with the Fragment (Hash)](http://medialize.github.io/URI.js/docs.html#fragment-abuse) and give [URL fragments](http://medialize.github.io/URI.js/docs.html#fragment-abuse-uri) a try:

```js
var URI = require('uri.js/src/URI.fragmentURI.js');
// turn off the default "!" causing the usual hashbang #!
URI.fragmentPrefix = '';

var uri = new URI('https://debug.test.com/#/accept');
var fragment = uri.fragment(true);
fragment.addSearch({ param: "a" });
uri.toString() === 'https://debug.test.com/#/accept?param=a'
```
If you don't want to use the plugin, you can always do this manually:

```js
var URI = require('uri.js');
var uri = new URI('https://debug.test.com/#/accept');
var fragment = new URI(uri.fragment());
fragment.addSearch({ param: "a" });
uri.fragment(fragment.toString());
uri.toString() === 'https://debug.test.com/#/accept?param=a';
```
