### ISSUE TITLE
can't import it in node.js platform

### ISSUE THREAD

**Issue by zzzgit** [medialize/URI.js#336]
`npm install urijs --save`,and then,I can see  `"urijs": "^1.18.10"` in package.json.
and then,`var URI = require('urijs')`,it got an error,because the actual folder is `uri` not `urijs`

**Comment by rodneyrehm** [comment]
What error did you get? the following works fine for me:

```sh
➜  npm install urijs
/my/path
└── urijs@1.18.10

➜  echo "var URI = require('urijs'); console.log(URI.version);" > index.js

➜  node index.js
1.18.10
```

**Comment by zzzgit** [comment]
maybe I have been confused by other packages
