### ISSUE TITLE
setFragment is missing

### ISSUE THREAD

**Issue by shtse8** [medialize/URI.js#338]
as there is `setQuery` and `setSearch`, but missing `setFragment` in the fragment plugin. it is useful when I want to change the value of a fragment, while `addFragment` can't do it. At the moment, I need to `removeFragment` and then `addFragment` to work like `setFragment`.

**Comment by rodneyrehm** [comment]
are you looking for [`uri.fragment('new-hash')`](http://medialize.github.io/URI.js/docs.html#accessors-hash)?

**Comment by shtse8** [comment]
Not exactly. I am looking for `setFragment` of the Fragment plugin. It woild setting a data in fragment but not setting the whole fragment.

**Comment by shtse8** [comment]
https://www.domain.com/#?a=1

`uri.setFragment("a", 2)`

the result will be

https://www.domain.com/#?a=2
