### ISSUE TITLE
Resolving issue

### ISSUE THREAD

**Issue by ArmorDarks** [medialize/URI.js#343]
I'm not sure is it per design, or a bug.

When uri resolved within constructor with relative url, it loses a portion of url.

Few examples:

```js
URI('new', 'http://test.dev/test/inner/path').valueOf()
// result `http://test.dev/test/inner/new`, expected `http://test.dev/test/inner/path/new`
URI('../new', 'http://test.dev/test/inner/path').valueOf()
// result `http://test.dev/test/new`, expected `http://test.dev/test/inner/new`
```

In same time, adding trailing slash to firt argument for some reason fixes the issue:

```js
URI('new', 'http://test.dev/test/inner/path/').valueOf()
// result correct `http://test.dev/test/inner/path/new`
URI('../new', 'http://test.dev/test/inner/path/').valueOf()
// result correct `http://test.dev/test/inner/new`
```

And root-relative urls also works perfectly:

```js
URI('/new', 'http://test.dev/test/inner').valueOf()
// result correct `http://test.dev/new`
```

My assumption that it happens, because URI.js treats paths without trailing slash as _filename_, right? And nothing can be done about it?

**Comment by rodneyrehm** [comment]
> My assumption that it happens, because URI.js treats paths without trailing slash as filename, right?

that's correct (and intended).

> And nothing can be done about it?

well, simply by looking at the string `/foo/bar` we can't say if `bar` is a file or a directory.

When you request such a path from a web server it usually redirects you to `/foo/bar/` in case of directories, so that the browser can properly resolves relative resources.

**Comment by ArmorDarks** [comment]
Thanks, just wanted to ensure.
