### ISSUE TITLE
Use of Number.isInteger limits browser support

### ISSUE THREAD

**Issue by jeff-phillips-18** [medialize/URI.js#350]
The Number.isInteger() method is not supported in Internet Explorer 11 and earlier versions. Looks like the use was added in version 1.18.11

**Comment by spadgett** [comment]
MDN has this as a polyfill

```js
  return typeof value === 'number' && 
    isFinite(value) && 
    Math.floor(value) === value;
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger#Polyfill

**Comment by rodneyrehm** [comment]
This was introduced in #345 and I'm sorry to say that the last couple of months doing ES6-only has made me completely oblivious to this - sorry.

@jeff-phillips-18 @spadgett does either one of you want to send a PR for this?

**Comment by jeff-phillips-18** [comment]
@rodneyrehm I will send a PR shortly

**Comment by maiamcc** [comment]
(...for anyone who cares (probably very few folks), also experiencing this problem on phantomjs 2.1.1.)

**Comment by rodneyrehm** [comment]
fixed in [v1.18.12](https://github.com/medialize/URI.js/releases/tag/v1.18.12)

**Comment by ArmorDarks** [comment]
To be honest, not sure this is right thing to do. Support of older browsers should be concern of consumer. I'd rather maintained list of required polyfills for some older (but still used) browsers.

Adding [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger#Polyfill) in own script isn't that hard, and if developer supporting older browsers, he will have file with other IE-related polyfills anyway.

In foresight, I agree that this is very small change, but in future more and more such changes can occur and we might end up with something bloated, like jQuery, packed with dozens of workarounds.

**Comment by nebulousdog** [comment]
Thanks @rodneyrehm! Needed this fix for phantomjs as well.
