### ISSUE TITLE
No direct way to update query strings

### ISSUE THREAD

**Issue by sravan559** [medialize/URI.js#353]
The current version of URI.js supports removing query string and adding query strings. It would be nice to have the option to update query string as well rather than having to remove existing one (`removeQuery()`) and add it with new value (`addQuery()`).

**Comment by rodneyrehm** [comment]
[`setQuery`](http://medialize.github.io/URI.js/docs.html#search-set) is not what you're looking for?

**Comment by sravan559** [comment]
Looks like it is. I didn't read the documentation thoroughly.  Thanks! 

And I was searching for `update` assuming there would be an option to update the query params (would be nice if updateQuery can be an alias). 

I am going to close the issue. 😄
