### ISSUE TITLE
can't parse a domain with {}

### ISSUE THREAD

**Issue by dietah** [medialize/URI.js#357]
We have been using URI.js for some years now to parse map layer urls.
These contain {s} {x} {y} {z} parameters and are auto-replaced by leaflet or mapbox.

Now, suddenly our code breaks when updating an app because of the change in [#344](https://github.com/medialize/URI.js/issues/344)

Is there a way to allow these characters again? Or a least provide us with the option to define the allowed characters on which the url is valid.

Thanks

**Comment by rodneyrehm** [comment]
Hey There!

I'm currently on vacation so nothing is happening in the next 2 weeks. Please stick to [v1.18.10](https://github.com/medialize/URI.js/releases/tag/v1.18.10) for now. I'm closing this issue, because it's already tracked in #354. I'm sorry for the inconvenience :(

**Comment by dietah** [comment]
Hi, seems like I missed that a similar issue was already created.

No worries, enjoy your vacation!
