### ISSUE TITLE
setSearch - Duplicate values in array 

### ISSUE THREAD

**Issue by rudovjan** [medialize/URI.js#358]
Hello there!

I was trying to do something like this 
```
new URI('foo').addSearch('a', [1, 1]).toString()
```

I was expecting two 'a' in URL, but what I got is

Got
```
new URI('foo').addSearch('a', [1, 1]).toString()
"foo?a=1"
```

Expected
```
new URI('foo').addSearch('a', [1, 1]).toString()
"foo?a=1&a=1"
```

Did I miss something?

**Comment by rodneyrehm** [comment]
You're looking for the `URI.duplicateQueryParameters` option or `URI().duplicateQueryParameters()` method described in [`URI.buildQuery()`](duplicateQueryParameters)

**Comment by rudovjan** [comment]
Thank you very much! It helped!
