### ISSUE TITLE
Change URL without refreshing page?

### ISSUE THREAD

**Issue by g5400658** [medialize/URI.js#361]
I want to add/update a parameter to the current URL without refreshing the page.

Is this something this plugin is capable of? If so, how? Because I can't find documentation on how to do this.

**Comment by rodneyrehm** [comment]
You're likely looking for [History.replaceState()](https://developer.mozilla.org/en-US/docs/Web/API/History_API). While URI.js can help you *construct* the URL, it cannot interact with the browser for you.

```js
var newUrl = URI().addQuery('hello', 'world').resource();
history.replaceState(null, "the new title", newUrl);
```
