### ISSUE TITLE
Using URI.js to show/hide DIVs

### ISSUE THREAD

**Issue by vilav** [medialize/URI.js#362]
Hello

Noob Question: is there a way to setup URI.js such that if the URL contains a certain parameter it would show /hide a specific DIV?

So xyz.com?show=**_apple_**&hide=**_banana_**

would show <div data-uri="apples">
and hide <div data-uri="banana">

thanks for the guidance

**Comment by rodneyrehm** [comment]
questions like these are better asked on http://stackoverflow.com/

```js
// get ?show=apple&hide=banana as { show: 'apple', hide: 'banana' }
var query = URI().query(true);

// get your DIVs
var apple = document.getElementById('apple');
var banana = document.getElementById('banana');

// hide your DIVs
apple.hidden = query.hide === 'apple';
banana.hidden = query.hide === 'banana';
```

**Comment by vilav** [comment]
Thanks @rodneyrehm! Missed out some context on the question, have updated it to indicate using a data- parameter. can the snippet you mentioned play well with data- parameter?

**Comment by rodneyrehm** [comment]
@vilav I won't post ready to use code for problems that have nothing to do with URI.js. Please ask these questions on StackOverflow (or elsewhere).

That said, you're looking for [`document.querySelector()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector) and [Attribute Selectors](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Attribute_selectors) to solve that data attribute (not parameter) problem.
