### ISSUE TITLE
TypeError: text.replace is not a function

### ISSUE THREAD

**Issue by abdulwahidgul24085** [medialize/URI.js#369]
Hi can you help me with the bug, it has some problem with the URI.js file on line 189 of the file.
 return text.replace(trim_expression, '');
                ^

TypeError: text.replace is not a function
   
![image](https://user-images.githubusercontent.com/6042059/44986698-19f54c80-af9e-11e8-83c7-2acf3c69f0e7.png)

**Comment by rodneyrehm** [comment]
what's the stack trace of that error? something seems to be calling `trimSlashes()` without providing a string as first argument.

**Comment by abdulwahidgul24085** [comment]
I encountered this error with the js-stellar-sdk. But this was a cause of a missing call back. I am still a learner in js, so thought would report that problem.

**Comment by rodneyrehm** [comment]
thx! good look :)
