### ISSUE TITLE
ESM exports

### ISSUE THREAD

**Issue by ioanlucut** [medialize/URI.js#373]
First of all, thank you for this library.

I would like to ask if is possible to provide ESM exports, so that we can include in our project only what we need, and having tree shaking enabled, in order to shrink the end js file.

Thank you!

**Comment by rodneyrehm** [comment]
I think this is already tracked in #172 and no progress has been made to this day. I'm not sure I'll ever get around to this, as [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) and [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) cover most of my needs these days. I'm open to supporting anyone willing to look into rewriting URI.js in ES6, though.

**Comment by ioanlucut** [comment]
@rodneyrehm thanks for your answer. I will close this ticket as won't do, then.
