### ISSUE TITLE
Url should ignore the fullwidth code

### ISSUE THREAD

**Issue by crossle** [medialize/URI.js#378]
fullwith symbol should be ingore, like https://google.com，你好 
https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms

**Comment by rodneyrehm** [comment]
Where should that symbol be ignored specifically?

**Comment by crossle** [comment]
like （https://www.googoe.com/CN_UST）；it's use fullwidth symbol `（ `and` ）`

**Comment by rodneyrehm** [comment]
To make sure i understood correctly: you'd like [URI.withinString()](http://medialize.github.io/URI.js/docs.html#static-withinString) to *categorically exclude* fullwidth characters (`U+FF00` - `U+FFEF`) from URLs.

This could be achieved by extending [`URI.findUri.end`](https://github.com/medialize/URI.js/blob/gh-pages/src/URI.js#L236):

```js
URI.findUri.end = /[\s\r\n]|[\uFF00-\uFFEF]|$/;

var text = "like （https://www.googoe.com/CN_UST）；it's use fullwidth symbol `（ `and` ）`"
  + "\n"
  + "fullwith symbol should be ingore, like https://google.com，你好 "
  + "https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms";

var result = URI.withinString(text, url => {
  console.log('found:', url);
  return '<a>' + url + '</a>';
});

console.log('replaced:', result);
```

which would output:

```
found: https://www.googoe.com/CN_UST
found: https://google.com
found: https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms
replaced: like （<a>https://www.googoe.com/CN_UST</a>）；it's use fullwidth symbol `（ `and` ）`
fullwith symbol should be ingore, like <a>https://google.com</a>，你好 <a>https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms</a>
```

It should be noted that neither github's URL matcher, nor Chrome Dev Tools' URL matcher behaves that way. Both *include* fullwidth characters. Also, [URL](https://url.spec.whatwg.org/) accepts fullwidth characters:

```js
var url = new URL("https://www.googoe.com/CN_UST</a>）；it's");
console.log(url.href);
// https://www.googoe.com/CN_UST%3C/a%3E%EF%BC%89%EF%BC%9Bit's
```
