### ISSUE TITLE
Path doesn't contain trailing slash when set via .path()

### ISSUE THREAD

**Issue by kross-italk** [medialize/URI.js#379]
It's possible this is desired and documented behavior, but I couldn't find anything explicitly about it and I was confused. I am using a non-regular protocol with a dash in it, so this should be a faithful reproduction of my test data. I would have expected setting .path() to not require me to pass in the slash. 

`var a = new URI('example-uri://username:password@127.0.0.1:8080/01234')
a.path()
"/01234"
a.path('01234')
a.path();
"01234"
`

**Comment by rodneyrehm** [comment]
I can see how this is irritating. Consider the following:

```js
var a = new URI('example-uri://username:password@127.0.0.1:8080/01234')
console.log(a.toString())
// fully qualified URL
// "example-uri://username:password@127.0.0.1:8080/01234"

a.authority('').scheme('')
console.log(a.toString())
// absolute path
// "/01234"

a.path('01234')
console.log(a.toString())
// relative path
// "01234"
```

**Comment by kross-italk** [comment]
I'll stick with including the slash when using .path (or path constructor option) and a comment that this is intended. Thanks!
