### ISSUE TITLE
URI.min.js 1.19.4 throws "does not have either property: href, src, action, cite"

### ISSUE THREAD

**Issue by kavika-1** [medialize/URI.js#404]
Since 1.19.4, URI.min.js is throwing `does not have either property: href, src, action, cite`
Upon investigation, it appears that the npm package dist folder contains a URI.min.js that suddenly includes jquery.URI.js.
Looking back to 1.19.2 (and presuming prior builds), the min version did not include jquery.URI.js, which we'd think is the expected behavior.

**Comment by rodneyrehm** [comment]
🤦 thanks for pointing this out ❤️ 

Should be fixed in [v1.19.5](https://github.com/medialize/URI.js/releases/tag/v1.19.5). Sorry for the inconvenience :(

**Comment by kavika-1** [comment]
Wow that was quick!  <❤️/> for fixing it...
