### ISSUE TITLE
ReferenceError: URI is not defined

### ISSUE THREAD

**Issue by marcalj** [medialize/URI.js#5]
C'mon, add your library in the site! :)

It's useful open console and test the examples of documentation.

**Comment by SurajSokasaneCB** [comment]
What is solution for this?

**Comment by pklejnowski** [comment]
Same issue here.

**Comment by NSExceptional** [comment]
Not quite related, but is anyone able to get this working in JSFiddle? I found this one with it already included, but it gives the error in this post in the console: https://jsfiddle.net/ezanker/smz2D/
